# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='customer_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.Profile'),
        ),
    ]
