# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 14:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaigns', '0010_landingpage_optimize'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='campain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Campaigns.Campaigns'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='origin',
            field=models.CharField(max_length=40, validators=[django.core.validators.URLValidator]),
        ),
    ]
