# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaigns', '0011_auto_20170723_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='choices',
            field=models.CharField(choices=[('3', 'Public'), ('1', 'Personal'), ('2', 'Private')], default='1', max_length=10),
        ),
    ]
